In [9]:
# Import dependencies
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import psycopg2

from sqlalchemy import create_engine

from config import db_password

In [11]:
# Read the songs_normalize.csv

songs1_df = pd.read_csv("Resources/songs_normalize_1.csv")
songs2_df = pd.read_csv("Resources/songs_normalize_2.csv")

display(songs1_df)
display(songs2_df)

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806
...,...,...,...,...,...,...,...,...,...,...
1936,Jonas Brothers,Sucker,181026,False,2019,79,0.842,0.734,1,-5.065
1937,Taylor Swift,Cruel Summer,178426,False,2019,78,0.552,0.702,9,-5.707
1938,Blanco Brown,The Git Up,200593,False,2019,69,0.847,0.678,9,-8.635
1939,Sam Smith,Dancing With A Stranger (with Normani),171029,False,2019,75,0.741,0.520,8,-7.513
1940,Post Malone,Circles,215280,False,2019,85,0.695,0.762,0,-3.497

,song,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Oops!...I Did It Again,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop
1,All The Small Things,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Breathe,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country"
3,It's My Life,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal"
4,Bye Bye Bye,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop
...,...,...,...,...,...,...,...,...,...
1936,Sucker,0,0.0588,0.0427,0.000000,0.1060,0.952,137.958,pop
1937,Cruel Summer,1,0.1570,0.1170,0.000021,0.1050,0.564,169.994,pop
1938,The Git Up,1,0.1090,0.0669,0.000000,0.2740,0.811,97.984,"hip hop, country"
1939,Dancing With A Stranger (with Normani),1,0.0656,0.4500,0.000002,0.2220,0.347,102.998,pop
1940,Circles,1,0.0395,0.1920,0.002440,0.0863,0.553,120.042,hip hop

In [10]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/songs_data"

In [5]:
#Create the database engine with the following:
engine = create_engine(db_string)

In [6]:
# Find null values
for column in songs1_df.columns:
    print(f"Column {column} has {songs1_df[column].isnull().sum()} null values")

Column artist has 0 null values
Column song has 0 null values
Column duration_ms has 0 null values
Column explicit has 0 null values
Column year has 0 null values
Column popularity has 0 null values
Column danceability has 0 null values
Column energy has 0 null values
Column key has 0 null values
Column loudness has 0 null values

In [7]:
songs1_df.to_sql(name='songs1', con=engine, if_exists='replace')
songs2_df.to_sql(name='songs2', con=engine, if_exists='replace')

941

In [16]:
# Joining songs1 and songs2 tables
SELECT songs1_df, songs2_df
FROM songs1
FULL OUTER JOIN songs
ON song = song;

SyntaxError: invalid syntax (2860147822.py, line 2)